### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by wconly** [LinkClinton/IGP-DirectX12-Chinese#2]
您好，
人邮的异步社区已经拿到本书的中文版权了，有人花了近一年的时间本书已翻译完成，正在校稿。大约在秋季成书。
我不想打击您的积极性，也知道您是本着为大家服务态度免费公开翻译的，但还是希望跟您说一声。
希望不要造成误会
谢谢，见谅……
http://www.epubit.com.cn/book/details/4617

**Comment by LinkClinton** [comment]
嗯，这是个好事情。我做这事情原本是为了锻炼自己和学习的。

**Comment by wconly** [comment]
好的，
您的文笔也许比书的译者要好……
其实这利益跟我关系也不是很大，不过我的意思是，要是整本都有人翻译了，估摸这书也就没人买了……哈哈~
最后提醒您一下，这本书的错误不少……要小心……

**Comment by wconly** [comment]
您别误会，也许说得太严重了，您可以继续您的学习和翻译，只要不是整本翻译，我估摸不会有什么的……
另外我也不是出版社派来的，哈哈……
别误会……

**Comment by LinkClinton** [comment]
这本书的错误不少是指的我翻译的还是原书的？原书有部分直接将DX11版本抄过来了...

**Comment by wconly** [comment]
您翻译的粗看看到有一个：
“Direct3D和硬件驱动将会把Direct3D的指令翻译成可以被CPU理解的机器语言“
应该是：
”Direct3D和硬件驱动将会把Direct3D的指令翻译成可以被GPU理解的机器语言“

原书也有不少，有笔误，也有严重的理解错误。也许跟作者从预览版开始写有关系，那时的API有的跟现在的有少量区别。
要不然中文版早就可以出了，哈哈哈……

您可以继续翻，不全翻应该就可以了吧？
为了您自己的爱好，和网友的意愿嘛。
现在貌似“福尔康”的书不是很多……即是有，评价似乎也不那么高
其实原理都一样，就是api和实现的细节策略不一样……

**Comment by LinkClinton** [comment]
感谢你的提醒和你发现的问题。这个我估计是看错了..这两个确实有点像。

我大概应该不会全部翻译，因为有人有正规翻译了，我也觉得我没有必要去纠结于原文，而应该纠结于个人的想法。

再次感谢你的提醒和发现的问题。
