### ISSUE TITLE
忽略这个吧

### ISSUE THREAD

**Issue by LinkClinton** [LinkClinton/IGP-DirectX12-Chinese#3]
忽略

**Comment by wconly** [comment]
您说得太严重了，只要不是全翻译应该没有什么大问题。
站在我这个位置只是希望这本书不会卖不出去，还不能打击您学习的积极性。
或者，您可以看看这个：http://www.epubit.com.cn/book/details/4292
正缺人手！

**Comment by LinkClinton** [comment]
OPENGL...这个我不会，我表示要跟随时代学习Vulkan。
