### ISSUE TITLE
能不能加个QQ或者QQ群 讨论一下技术？

### ISSUE THREAD

**Issue by LigaLiao** [LinkClinton/IGP-DirectX12-Chinese#4]
RT

**Comment by LinkClinton** [comment]
泥有Line么？QQ表示不怎么用

**Comment by LigaLiao** [comment]
没有 Line被墙了   绝大部分vpn也挂了 没法用
你在日本？

**Comment by LigaLiao** [comment]
以后邮件联系吧
现在我想请教一下一个问题，看这个
http://www.opengpu.org/forum.php?mod=viewthread&tid=18595&page=1

**Comment by LinkClinton** [comment]
没，用的安卓版本目前还是可以用的.

设置描述符堆的话，是要求你在使用描述符表之前要把那个对应的堆绑定到渲染管道上。
至于那里面说的你不使用这个也可以绑定纹理的话，这就好比在做不知道结果的事情。
也就是说你就算不绑定最后没问题不代表在任何情况下都不会出问题。已经测试在一个堆里面放2个CBV一个SRV的时候如果不设置堆的话就会绘制失败。
