### ISSUE TITLE
请问可以协作翻译吗？

### ISSUE THREAD

**Issue by lijipeng787** [LinkClinton/IGP-DirectX12-Chinese#6]
之前完整读过DirectX11和DirectX10版龙书，并一直在学习DirectX11和12，本书刚刚出的时候也大致看过一遍，希望能够帮一些忙。

**Comment by LinkClinton** [comment]
首先表示热烈的欢迎并且高兴。

但是由于我没有过这样的经历，所以不知道你是想以什么形式来协作翻译。
希望你能够说明下，以便我们能够不浪费资源。

**Comment by lijipeng787** [comment]
非常感谢回复。
1.您是否希望完整的翻译这本书呢？我看到计划只翻译其中一部分，且计划目前完成度6/10。
2.参考其他翻译项目的形式，我个人比较推荐认领单独章节。
3.最重要的是文本格式问题，这个可以直接参考您已经完成的翻译部分，保持一致即可。
4.术语翻译（按照已完成的既有翻译/保持英文？），代码片段格式（图片/文本？）

**Comment by LinkClinton** [comment]
1.起初是确实只打算翻译10章，但是也只是初步的计划(毕竟要看有没有空余时间)。因此你要参与的话，肯定是不局限于列表里的。不过这里我希望的是不要去选择前三章。
2.形式主要由你自己选择，但是我现在不知道你对于DX12是没有了解还是已经很了解了。因此这里我给出两个方向吧，如果你是还没有去了解的，那么就先帮我校验下前面的章节(就是关于DX12基础知识部分)。
如果你已经很了解了，那么你可以自己选择章节(不要选择我正在做的或者做完的就好了)，如果你不想自己选我也可以指定。
3.关于文本格式的话，之后我会提交一个format.md文件来具体说明(其实早该写了....)。
4.术语翻译等问题都会在format.md里面解释。

除了这些还有一些你需要注意的是，第一，在完成所有的初步翻译后我们会进行校验，因此做好自己的成果可能被改的面目全非的准备QAQ。第二，就是翻译的时候不要太注重原文的语言，大概意思就是说最好能够和原文有一些差异，以及最好能够加上自己的看法使得翻译不那么刻板吧。

最后祝你翻译愉快咯。你可以看到我最近很少动工，我到6月份之前是很难抽出时间的，因此如果有一些疑问什么的我可能回答的不会很及时，请谅解。

**Comment by lijipeng787** [comment]
1.我是个学生，对dx12的了解没有那么深入，只是把一些之前用dx11写的demo用dx12重写了（我已经一年没有动过dx12的项目了）。
2.所以我可以按照你的建议从校对你已经翻译完成的部分开始，有一个熟悉的过程后，再对后面的章节进行翻译。
3.如果可以的话，希望你可以提出一些校对方面的期望。

**Comment by LinkClinton** [comment]
校对的期望啊，我觉得能够找到我当时没有发现的错误或者理解不对的地方矫正过来，以及关于格式上的疏漏什么等。反正我估计很多很多....

format.md已经提交，你可以去看看。

其实我也是学生，所以我觉得我们差不多的其实2333.

**Comment by lijipeng787** [comment]
已经开始在校对第四章，速度可能有点慢，有问题会及时和你沟通。

**Comment by LinkClinton** [comment]
好嘞

**Comment by lijipeng787** [comment]
1.目前主要是调整已有翻译的中文表述吧，我的目标是不要太过严肃专业也不要太过口语化，一个段落能够前后联系，通顺阅读即可。
2.有dx11经验，尤其是看过以前版本龙书的话，其实直接fork作者的代码+msdn可能比看这本书更有效（个人意见），所以可以考虑下这个翻译版本的受众，然后对内容进行适当的扩充/缩减，或者对随书代码的一些关键部分进行讲解，感觉删掉了好几页的代码后空荡荡的。。。。（当然这是长远计划的一个小建议，不必现在进行）

**Comment by LinkClinton** [comment]
对。
关于代码方面的话，原则是尽量简洁以及表达准确即可，语法要求甚至也可以不那么严格。
关于你提的建议可以在翻译的时候开始，反正最后还是要校正的。不过关于代码的原则是最好不要去打破的，我觉得在书(PDF)里面放代码是真的影响阅读，但是web下面还是不错。

**Comment by lijipeng787** [comment]
ok，这几天中断了几天，没能及时回复。代码的问题了解，先按照目前的办法做。

**Comment by lijipeng787** [comment]
a2e8a18 
1.校对的进度比想象中的慢，而且这一阵有点忙，我过几天会做一个里程碑，希望可以约束下自己的进度。上面的push是我目前校对的比较完整的一部分，并不多，你可以先看一看效果。
2.我设法总结一下你我翻译方式不一样的地方，翻译术语我尽量不会改动（除非出现错误或者有早已使用的更通用的版本），我会做改动。

**Comment by LinkClinton** [comment]
了解，我也会注意稍微严谨点。
进度的话也没有什么要求，但最好能有稳定的速度(现在的我是做不到了QAQ)。

**Comment by LinkClinton** [comment]
哦，对了。前面部分的内容中可能有一些数学公式是图片，到时候你顺便用latex替换掉图片QAQ，以及有一些公式的呈现很不美观，例如一些公式要居中但是没有居中等等。

**Comment by lijipeng787** [comment]
ea792ae5f7065674b63c104480a98fb31248963e

1.上面是最新的push，每次只推一部分，这样对你来讲review容易一些，校对的有问题可以等你有时间在这里讨论。
2.了解，公式方面我需要学习一下，之前还没用过latex。
2.我尽量以稳定的间隔提交。

**Comment by lijipeng787** [comment]
我会关掉这个issue，每一章的校对在一个issue中，未来完成每一章的校对后关闭对应issue。

**Comment by LinkClinton** [comment]
好，关于你的每次提交我会在提交的那里留下回复。
